/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import 'sst';
export {};
declare module 'sst' {
  export interface Resource {
    PersonsApi: {
      type: 'sst.aws.ApiGatewayV2';
      url: string;
    };
    addPersonDlq: {
      type: 'sst.aws.Queue';
      url: string;
    };
    addPersonQueue: {
      type: 'sst.aws.Queue';
      url: string;
    };
    ddbEnricher: {
      name: string;
      type: 'sst.aws.Function';
    };
    ddbStreamDlq: {
      type: 'sst.aws.Queue';
      url: string;
    };
    personsTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
  }
}
